CREATE TABLE partidentifier (`PartID` TEXT NULL, `IdentifierName` TEXT NULL, `IdentifierValue` TEXT NULL, `CreationDate` TEXT NULL);
CREATE TABLE doi (`EntityType` TEXT NULL, `EntityID` TEXT NULL, `DOI` TEXT NULL, `CreationDate` TEXT NULL);
CREATE TABLE creatoridentifier (`CreatorID` TEXT NULL, `IdentifierName` TEXT NULL, `IdentifierValue` TEXT NULL, `CreationDate` TEXT NULL);
CREATE TABLE part (`PartID` TEXT NULL, `ItemID` TEXT NULL, `ContributorName` TEXT NULL, `SequenceOrder` TEXT NULL, `SegmentType` TEXT NULL, `Title` TEXT NULL, `ContainerTitle` TEXT NULL, `PublicationDetails` TEXT NULL, `Volume` TEXT NULL, `Series` TEXT NULL, `Issue` TEXT NULL, `Date` TEXT NULL, `PageRange` TEXT NULL, `StartPageID` TEXT NULL, `LanguageName` TEXT NULL, `SegmentUrl` TEXT NULL, `ExternalUrl` TEXT NULL, `DownloadUrl` TEXT NULL, `RightsStatus` TEXT NULL, `RightsStatement` TEXT NULL, `LicenseName` TEXT NULL, `LicenseUrl` TEXT NULL, `RightsHolder` TEXT NULL, `BarCode` TEXT NULL);
CREATE TABLE item (`ItemID` TEXT NULL, `TitleID` TEXT NULL, `ThumbnailPageID` TEXT NULL, `BarCode` TEXT NULL, `MARCItemID` TEXT NULL, `CallNumber` TEXT NULL, `VolumeInfo` TEXT NULL, `ItemURL` TEXT NULL, `ItemTextURL` TEXT NULL, `ItemPDFURL` TEXT NULL, `ItemImagesURL` TEXT NULL, `LocalID` TEXT NULL, `Year` TEXT NULL, `InstitutionName` TEXT NULL, `ZQuery` TEXT NULL, `CreationDate` TEXT NULL, `CopyrightStatus` TEXT NULL, `RightsStatement` TEXT NULL, `LicenseType` TEXT NULL, `RightsHolder` TEXT NULL);
CREATE TABLE partcreator (`PartID` TEXT NULL, `CreatorID` TEXT NULL, `CreatorName` TEXT NULL, `CreationDate` TEXT NULL);
CREATE TABLE creator (`TitleID` TEXT NULL, `CreatorID` TEXT NULL, `CreatorType` TEXT NULL, `CreatorName` TEXT NULL, `CreationDate` TEXT NULL);
CREATE TABLE subject (`TitleID` TEXT NULL, `Subject` TEXT NULL, `CreationDate` TEXT NULL);
CREATE TABLE title (`TitleID` TEXT NULL, `MARCBibID` TEXT NULL, `MARCLeader` TEXT NULL, `FullTitle` TEXT NULL, `ShortTitle` TEXT NULL, `PublicationDetails` TEXT NULL, `CallNumber` TEXT NULL, `StartYear` TEXT NULL, `EndYear` TEXT NULL, `LanguageCode` TEXT NULL, `TL2Author` TEXT NULL, `TitleURL` TEXT NULL, `CreationDate` TEXT NULL);
CREATE TABLE page (`PageID` TEXT NULL, `ItemID` TEXT NULL, `SequenceOrder` TEXT NULL, `Year` TEXT NULL, `Volume` TEXT NULL, `Issue` TEXT NULL, `PagePrefix` TEXT NULL, `PageNumber` TEXT NULL, `PageTypeName` TEXT NULL, `CreationDate` TEXT NULL);
CREATE INDEX idx_page_pageid ON page (PageID);
CREATE INDEX idx_page_itemid ON page (ItemID);
CREATE INDEX idx_page_type ON page (PageTypeName);
CREATE INDEX idx_page_year ON page (Year);
CREATE TABLE titleidentifier (`TitleID` TEXT NULL, `IdentifierName` TEXT NULL, `IdentifierValue` TEXT NULL, `CreationDate` TEXT NULL);
CREATE INDEX "title_issn_idx" ON titleidentifier(IdentifierName ASC);
CREATE INDEX "title_titleid_idx" ON titleidentifier(TitleID ASC);
CREATE INDEX "title_idx" ON title(TitleID ASC);
CREATE TABLE partpage (`PartID` TEXT NULL, `PageID` TEXT NULL, `ItemID` TEXT NULL, `SequenceOrder` TEXT NULL, `CreationDate` TEXT NULL);
CREATE INDEX "partpage_part_idx" ON partpage(PartID ASC);
CREATE INDEX "partpage_page_idx" ON partpage(PageID ASC);
CREATE INDEX "partpage_item_idx" ON partpage(ItemID ASC);
CREATE INDEX "item_item_idx" ON item(ItemID ASC);
CREATE INDEX "item_title_idx" ON item(TitleID ASC);
